# Generated by Django 4.0 on 2022-05-22 23:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('login_date', models.CharField(db_column='login_date', default=django.utils.timezone.now, max_length=255)),
            ],
        ),
    ]
